//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitViewFilters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitViewFilters.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter creation error:.
        /// </summary>
        public static string ErrorFilterCreation1 {
            get {
                return ResourceManager.GetString("ErrorFilterCreation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nPlace in the model as minimum one element in the category:.
        /// </summary>
        public static string ErrorFilterCreation2 {
            get {
                return ResourceManager.GetString("ErrorFilterCreation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nRequested parameter:.
        /// </summary>
        public static string ErrorFilterCreation3 {
            get {
                return ResourceManager.GetString("ErrorFilterCreation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 64 values! Unable to create filters.
        /// </summary>
        public static string ErrorMore64values {
            get {
                return ResourceManager.GetString("ErrorMore64values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter Dim.BottomElevation.
        /// </summary>
        public static string ErrorNoBottomElevParam {
            get {
                return ResourceManager.GetString("ErrorNoBottomElevParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter Dim.TopElevation.
        /// </summary>
        public static string ErrorNoTopElevParam {
            get {
                return ResourceManager.GetString("ErrorNoTopElevParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No base level for the wall ID:.
        /// </summary>
        public static string ErrorNoWallBaseLevel {
            get {
                return ResourceManager.GetString("ErrorNoWallBaseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is available only on Viewplans.
        /// </summary>
        public static string ErrorOnlyViewplan {
            get {
                return ResourceManager.GetString("ErrorOnlyViewplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria Begins with is available only for text parameters.
        /// </summary>
        public static string ErrorRuleBeginsWithOnlyForText {
            get {
                return ResourceManager.GetString("ErrorRuleBeginsWithOnlyForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set view filters because the are defined in the view template.
        /// </summary>
        public static string ErrorViewTemplate {
            get {
                return ResourceManager.GetString("ErrorViewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many wall types! Should be lsee than 10.
        /// </summary>
        public static string ErrorWallsMoreThan10 {
            get {
                return ResourceManager.GetString("ErrorWallsMoreThan10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls are not selected..
        /// </summary>
        public static string ErrorWallsNotSelected {
            get {
                return ResourceManager.GetString("ErrorWallsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  beg.with .
        /// </summary>
        public static string FilterRuleBeginsWith {
            get {
                return ResourceManager.GetString("FilterRuleBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  equals .
        /// </summary>
        public static string FilterRuleEquals {
            get {
                return ResourceManager.GetString("FilterRuleEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls Dim.TopElevation equals.
        /// </summary>
        public static string FilterTitleWallTopElev {
            get {
                return ResourceManager.GetString("FilterTitleWallTopElev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create: \n.
        /// </summary>
        public static string MessageCreateFiltersFailed {
            get {
                return ResourceManager.GetString("MessageCreateFiltersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created filters:.
        /// </summary>
        public static string MessageCreateFiltersSuccess {
            get {
                return ResourceManager.GetString("MessageCreateFiltersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully deleted filters:.
        /// </summary>
        public static string MessageDeleteFiltersSuccess {
            get {
                return ResourceManager.GetString("MessageDeleteFiltersSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSV file.
        /// </summary>
        public static string TitleSelectCsvFile {
            get {
                return ResourceManager.GetString("TitleSelectCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create filter:.
        /// </summary>
        public static string TransactionCreateFilters {
            get {
                return ResourceManager.GetString("TransactionCreateFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string TransactionDeleteFilters {
            get {
                return ResourceManager.GetString("TransactionDeleteFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View colorize.
        /// </summary>
        public static string TransactionViewColorize {
            get {
                return ResourceManager.GetString("TransactionViewColorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls elevations.
        /// </summary>
        public static string TransactionWallsElevation {
            get {
                return ResourceManager.GetString("TransactionWallsElevation", resourceCulture);
            }
        }
    }
}
